### ISSUE TITLE
webpack support?

### ISSUE THREAD

**Issue by tommck** [angular/dgeni#159]
Webpack is more and more popular every day. I was surprised not to see a webpack loader to support generating documentation.

Are there any plans for this? 
I'm a webpack newbie at this point, so I'm not sure if I'm comfortable tackling this yet myself

**Comment by petebacondarwin** [comment]
Hi @tommck - what would you envision a webpack loader to do?

**Comment by tommck** [comment]
well, maybe not a loader (again, a webpack newb), but something to allow for generating the docs with webpack instead of gulp/grunt.  

Or, maybe better command-line support so we could do it with a straight npm script?

I don't want to have to add gulp/grunt to my project just support generating documentation if I can help it.

**Comment by petebacondarwin** [comment]
You can actually run dgeni from the command line if you like:

```bash
dgeni path/to/main-dgeni-package.js
```

The binary is distributed with the `dgeni` module.

But it is really quite simple to run dgeni from any node script:

```js
var Dgeni = require('dgeni');
var myPackage = require(path/to/mainpackage);
var dgeni = new Dgeni([myPackage]);
dgeni.generate();
```

**Comment by tommck** [comment]
Yeah, I really didn't think about just writing a tiny node script :)

**Comment by tommck** [comment]
That seems to work for me.  Now I just need to figure out all my other problems :)

**Comment by petebacondarwin** [comment]
Glad I could be of some help. Get in touch with other questions or issues.

**Comment by tommck** [comment]
With 617 open issues, it seems like issues will just get lost here.  I was pretty surprised that you responded so quickly.

Frankly, I have big problems with how difficult it seems to configure dgeni.  I was expecting it to be much easier to use than it is.

I just ported code to TypeScript from JavaScript and now the exact same comments don't work right (links in the docs are all off, getting multiple versions of the same thing in the docs, etc.)

**Comment by petebacondarwin** [comment]
There are only 19 issues on dgeni :-)
But then again all of the meat of the work is in the dgeni-packages repository.
The main problem that people have with dgeni is that there is no good starting point.
But once you are setup it is surprisingly versatile!

**Comment by tommck** [comment]
oh weird.. was looking at the wrong package!  Sorry :)

**Comment by Smolations** [comment]
Not sure why this was closed so soon. Yes, it is trivial to write a node script for this, however, when doing dev using the webpack-dev-server, having a dgeni plugin would be most helpful. I am working on my company's component library docs. We have created a custom application with custom design, and we had been previously using a gulp task to generate docs, and a watcher to trigger new docs generation (which creates a file for each file that exports a POJO with dgeni docs as strings; those then get imported into the app, and injected as html). We have now decided to change to webpack and the webpack-dev-server, so it seems we will have to have a gulp watcher which will undoubtedly have a race condition (and probably lose every time) when the bundle is re-created on file changes. Could this be considered again, or is all hope lost for now?

**Comment by petebacondarwin** [comment]
@Smolations - I am still not sure what the specification of such a loader would look like. Perhaps you could expand?

**Comment by Smolations** [comment]
@petebacondarwin Since there are only `require` statements for generated documentation (in my docs app), I have opted for creating a plugin instead of a loader. In order to replace the gulp task, the plugin would activate only when the `--watch` option is passed to webpack or the `webpack-dev-server` is used (which, I assume, does just that). Here is the general flow I am thinking:

In the webpack config, I add my plugin, allowing users to specify their own config(s):
```
    new DgeniDocsPlugin({
      config: './docs-config',
    }),
```

- The plugin creates the dgeni instance in the constructor, for later use in the `apply()` method.
- The plugin is configured to trigger on the `watch-run` event (e.g. `compiler.plugin('watch-run', (watching, callback) => {...}`)
- When a js file change (that contains ngdoc comments) is detected, docs generation is triggered, either on that file alone by altering the config a bit, or all files if the former is too complicated or impossible
- Since the plugin is async, the `callback()` would be triggered after dgeni has finished compiling the files that are eventually required within the docs app
- Then the rest of any remaining plugins are run from other events later in the webpack event pipeline

It is very possible that I have miscontrued the original purpose of this request, I just know that I am hitting a critical error when I attempt to import the passed-in config from the plugin options and create a dgeni instance from it. It may be more on the webpack side, but somewhere deep in the code webpack is having trouble interpreting the code that creates that dgeni instance from the passed-in config. I make sure to find the actual location of the config (so that the require statement in the plugin code doesn't barf), but I always get an error that says:
```
/home/vagrant/project/node_modules/webpack-sources/lib/ConcatSource.js:23
      return typeof item === "string" ? item : item.source();
                                                    ^

TypeError: item.source is not a function
    at /home/vagrant/project/node_modules/webpack-sources/lib/ConcatSource.js:23:50
```
When I remove the code that requires the config and instantiates a dgeni instance, no error is produced and the compilation completes (but the plugin does nothing at that point).

I have tried altering the code in my config in many ways such as commenting out blocks, removing blocks, etc., to no avail.  I can only assume that it has to do with the source code of dgeni itself, but perhaps it is something in the config. I guess I am just looking to make sure that there is a way to write a plugin that can successfully import a user's config and create a dgeni instance from it successfully, then run the docs generation.
